services:

  cache:
    build:
      context: ./
      dockerfile: ./docker/cache/Dockerfile
    container_name: braillest_cache
    env_file:
      - ./docker/cache/.env
    image: braillest_cache
    ports:
      - 6379:6379
    volumes:
      - ./data/cache:/data
    networks:
      - braillest

  core-backend:
    build:
      context: ./
      dockerfile: ./docker/core-backend/Dockerfile
    container_name: braillest_core_backend
    env_file:
      - ./docker/core-backend/.env
    image: braillest_core_backend
    ports:
      - 8000:8000
      - 443:443
    volumes:
      - ./src/core-backend:/braillest
      - ./logs/core-backend:/root/.symfony5/log
    networks:
      - braillest

  database:
    build:
      context: ./
      dockerfile: ./docker/database/Dockerfile
    container_name: braillest_database
    env_file:
      - ./docker/database/.env
    image: braillest_database
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - braillest

  database-viewer:
    container_name: braillest_database_viewer
    build:
      context: ./
      dockerfile: ./docker/database-viewer/Dockerfile
    image: braillest_database_viewer
    ports:
      - 8080:80
    env_file:
      - ./docker/database-viewer/.env

networks:
  braillest:
    name: braillest
